name: Build Lifecycle

on:
  pull_request:
  push:
    branches: [main]

jobs:
    build:
        name: Build (${{ matrix.os }})
        # Assumes we are using tags for releases
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
        steps:
            - name: Install Dependencies (Linux)
              if: matrix.os == 'ubuntu-latest'
              run: |
                sudo apt-get update
                sudo apt-get install -y libx11-dev libxkbfile-dev libsecret-1-dev fakeroot rpm

            - name: GitHub Checkout
              uses: actions/checkout@v3
              with:
                ref: '${{ github.head_ref }}'
                token: '${{ secrets.GH_PAT }}'

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20

            - name: npm install
              run: npm install

            - name: Add Mac OS Certs
              if: matrix.os == 'macos-latest'
              run: chmod +x ./scripts/add-mac-certs.sh && ./scripts/add-mac-certs.sh
              env:
                CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
                CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
